import {
  muxiumConclude,
  createQualityCardWithPayload,
  nullReducer,
  strategyData_appendFailure,
  strategyData_muxifyData,
  strategyFailed,
  strategySuccess,
  createAsyncMethodWithState,
} from 'stratimux';
import fs from 'fs/promises';
import path from 'path';
// Direct import from type file (NO barrel exports for tree-shaking)
import {
  type StrativerseState,
  type MuxonomyRegistryEntry,
  type MuxonomyRegistryResult,
  type IslandEntry,
} from '../strativerse.type';

export type StrativerseGenerateMuxonomyRegistryPayload = {
  scanPath?: string;
  outputPath?: string;
  dryRun?: boolean;
};

export type StrativerseGenerateMuxonomyRegistryDataField = MuxonomyRegistryResult;

const DEFAULT_OUTPUT_PATH = 'src/concepts/muxonomyRegistry.generated.ts';

async function scanMuxonomyFiles(scanPath: string): Promise<MuxonomyRegistryEntry[]> {
  const entries: MuxonomyRegistryEntry[] = [];

  try {
    const conceptDirs = await fs.readdir(scanPath, { withFileTypes: true });

    for (const dir of conceptDirs) {
      if (!dir.isDirectory()) continue;

      const conceptName = dir.name;
      const conceptDirPath = path.join(scanPath, conceptName);
      const muxonomyPath = path.join(conceptDirPath, `${conceptName}.muxonomy.ts`);

      let exists = false;
      try {
        await fs.access(muxonomyPath);
        exists = true;
      } catch {
        exists = false;
      }

      if (!exists) continue;

      const muxonomyContent = await fs.readFile(muxonomyPath, 'utf-8');

      const entry = parseMuxonomyFile(conceptName, muxonomyContent);
      if (entry) {
        entries.push({
          ...entry,
          muxonomyPath: `./${conceptName}/${conceptName}.muxonomy`,
        });
      }
    }
  } catch (error) {
    console.error('Error scanning muxonomy files:', error);
    throw error;
  }

  return entries.sort((a, b) => a.conceptName.localeCompare(b.conceptName));
}

function parseMuxonomyFile(conceptName: string, content: string): Omit<MuxonomyRegistryEntry, 'muxonomyPath'> | null {
  const configMatch = content.match(/export\s+const\s+(\w+Muxonomic)\s*:/);
  const creatorMatch = content.match(/export\s+function\s+(createMuxonomic\w+)\s*\(/);

  if (!configMatch || !creatorMatch) {
    console.warn(`Skipping ${conceptName}: missing muxonomic config or creator export`);
    return null;
  }

  const muxonomicConfigExport = configMatch[1];
  const createMuxonomicExport = creatorMatch[1];

  const hasNavigation = /navigation\s*:\s*\w+Navigation/.test(content) ||
                        /navigation\s*:\s*{/.test(content);

  const islandEntries = parseIslandEntries(conceptName, content);

  return {
    conceptName,
    muxonomicConfigExport,
    createMuxonomicExport,
    hasNavigation,
    islandEntries,
  };
}

function parseIslandEntries(conceptName: string, content: string): IslandEntry[] {
  const entries: IslandEntry[] = [];

  const pagesMatch = content.match(/pages\s*:\s*\[([\s\S]*?)\]/);
  if (!pagesMatch) {
    return entries;
  }

  const pagesBlock = pagesMatch[1];

  const pageEntryRegex = /componentPath\s*:\s*['"]([^'"]+)['"]/g;
  let match;
  while ((match = pageEntryRegex.exec(pagesBlock)) !== null) {
    const componentPath = match[1];
    const pageName = componentPath.split('/').pop() || 'main';
    const key = `islands/${conceptName}${pageName.toLowerCase() === 'landing' ? '' : '-' + pageName.toLowerCase()}`;

    entries.push({
      key,
      componentPath: `./concepts/${componentPath}.vue`,
    });
  }

  return entries;
}

function generateRegistryFileContent(entries: MuxonomyRegistryEntry[], generatedAt: string): string {
  const imports = entries.map(e =>
    `import { ${e.muxonomicConfigExport}, ${e.createMuxonomicExport} } from '${e.muxonomyPath}';`
  ).join('\n');

  const muxonomicsArray = entries.map(e => `  ${e.muxonomicConfigExport},`).join('\n');

  const islandEntries = entries
    .flatMap(e => e.islandEntries)
    .map(ie => `  '${ie.key}': '${ie.componentPath}',`)
    .join('\n');

  const islandCreators = entries.map(e =>
    `  '${e.conceptName}': ${e.createMuxonomicExport},`
  ).join('\n');

  const conceptCount = entries.length;
  const islandCount = entries.reduce((sum, e) => sum + e.islandEntries.length, 0);

  return `/**
 * Muxonomy Registry - AUTO-GENERATED BY STRATIVERSE
 * DO NOT EDIT MANUALLY
 *
 * Regenerate with: npm run strativerse:scan
 * Generated: ${generatedAt}
 *
 * Citation: SUITE-1-2-MUXONOMY-ISLANDS-ARCHITECTURE.md
 * Pattern: Build-time registry generation for Islands Architecture
 */

${imports}

import type { MuxonomicConfig, MuxonomicConcept } from './muxonomy/muxonomy.model';

/**
 * All registered muxonomy configurations with navigation
 * Used by: vue.principle.ts (shell generation)
 */
export const REGISTERED_MUXONOMICS: MuxonomicConfig[] = [
${muxonomicsArray}
];

/**
 * Vite entry points for island builds
 * Used by: vite.client.config.ts (rollupOptions.input)
 */
export const ISLAND_ENTRIES: Record<string, string> = {
${islandEntries}
};

/**
 * Island creators for client hydration
 * Used by: main.ts (island hydration)
 */
export const ISLAND_CREATORS: Record<string, () => MuxonomicConcept> = {
${islandCreators}
};

/**
 * Registry generation metadata
 */
export const REGISTRY_META = {
  generatedAt: '${generatedAt}',
  conceptCount: ${conceptCount},
  islandCount: ${islandCount},
};
`;
}

export const strativerseGenerateMuxonomyRegistry = createQualityCardWithPayload<
  StrativerseState,
  StrativerseGenerateMuxonomyRegistryPayload
>({
  type: 'Strativerse Generate Muxonomy Registry',
  reducer: nullReducer,
  methodCreator: () =>
    createAsyncMethodWithState(({ controller, action, state }) => {
      const scanPath = action.payload?.scanPath ?? state.conceptList.scanPath;
      const outputPath = action.payload?.outputPath ?? DEFAULT_OUTPUT_PATH;
      const dryRun = action.payload?.dryRun ?? false;

      if (action.strategy) {
        const strategy = action.strategy;

        scanMuxonomyFiles(scanPath)
          .then(async (entries) => {
            const generatedAt = new Date().toISOString();
            const content = generateRegistryFileContent(entries, generatedAt);

            if (!dryRun) {
              const fullOutputPath = path.resolve(process.cwd(), outputPath);
              await fs.writeFile(fullOutputPath, content, 'utf-8');
              console.log(`[StratiVERSE] Generated muxonomy registry: ${fullOutputPath}`);
              console.log(`[StratiVERSE] Found ${entries.length} concepts with ${entries.reduce((sum, e) => sum + e.islandEntries.length, 0)} islands`);
            } else {
              console.log('[StratiVERSE] Dry run - would generate:');
              console.log(content);
            }

            const dataField: StrativerseGenerateMuxonomyRegistryDataField = {
              entries,
              generatedAt,
              outputPath,
            };

            controller.fire(
              strategySuccess(
                strategy,
                strategyData_muxifyData(strategy, dataField)
              )
            );
          })
          .catch((error) => {
            console.error('[StratiVERSE] Error generating registry:', error);
            controller.fire(
              strategyFailed(strategy, strategyData_appendFailure(strategy, error))
            );
          });
      } else {
        controller.fire(muxiumConclude());
      }
    }),
});
