/**
 * Bare-Minimum Concept Generator — M2-A1-D2 Naming Wizard
 *
 * Per Q3 locked decision: wizard generates a BARE-MINIMUM concept stub for
 * the user's SCP — 3 files (type · state · concept) that compile clean and
 * can be muxified into client without further authoring.
 *
 * Pure functions emit file content as strings; M2-A1-D3 Clone + Rename
 * Engine performs the filesystem writes. Separation lets the wizard preview
 * the generated content (Conference render) before commit.
 *
 * Higher-Order Composition: generator owns NO state. NameDerivation flows
 * in from designationValidator.model.ts. Output is plain string content
 * keyed by relative file path.
 *
 * Citation: DIAMOND-TIER-MACRO-2.md M2-A1-D2 + Q3 (bare-minimum concept)
 * Citation: existing scsBridge concept pattern (exemplar for type/state/concept triple)
 * Citation: STRATIMUX-REFERENCE.md "🧩 Quality Creation Patterns"
 */
import type { NameDerivation } from './designationValidator.model';

// ============================================
// GENERATED FILE BUNDLE
// ============================================

export interface GeneratedConceptFile {
  relativePath: string;    // relative to SCP/src/ (e.g. "concepts/myResearch/myResearch.type.ts")
  content: string;
}

export interface GeneratedConceptBundle {
  files: GeneratedConceptFile[];
  conceptName: string;
  designation: string;
  fileCount: number;
}

// ============================================
// TEMPLATES
// ============================================

function generateTypeFile(d: NameDerivation): string {
  const PascalName = d.designation;
  const camelName = d.conceptName;
  return `/**
 * ${PascalName} Concept Type Definitions
 *
 * Bare-minimum SCP concept generated by SCS-Bridge Naming Wizard (M2-A1-D2).
 * Extend State + add payload types + register Qualities as the SCP grows.
 *
 * Higher-Order Composition: this concept stands as a base concept. Muxify
 * into client via createClientConcept's muxifyConcepts call. No 3rd tier.
 */
import type { Concept, Quality, AnyAction } from 'stratimux';

export const ${camelName}Name = '${camelName}';

export type ${PascalName}State = {
  // InductionState (Diametric Quality routing — required even for stub)
  actionQue: AnyAction[];
  filterKeys: string[];

  // Add SCP-specific state fields here as features land
  initializedAt: number;
};

export type ${PascalName}Qualities = Record<string, Quality<${PascalName}State, Record<string, unknown>>>;

export type ${PascalName}Concept = Concept<${PascalName}State, ${PascalName}Qualities>;
`;
}

function generateStateFile(d: NameDerivation): string {
  const PascalName = d.designation;
  const camelName = d.conceptName;
  const upperName = camelName.toUpperCase();
  return `/**
 * ${PascalName} Concept State Factory
 *
 * Bare-minimum state factory generated by SCS-Bridge Naming Wizard (M2-A1-D2).
 * Extend defaults + add FILTER_KEYS entries as state fields are added.
 */
import type { ${PascalName}State } from './${camelName}.type';

export function create${PascalName}State(): ${PascalName}State {
  return {
    actionQue: [],
    filterKeys: ${upperName}_FILTER_KEYS,
    initializedAt: Date.now(),
  };
}

export const ${upperName}_FILTER_KEYS: string[] = [
  'actionQue',
  'filterKeys',
];
`;
}

function generateConceptFile(d: NameDerivation): string {
  const PascalName = d.designation;
  const camelName = d.conceptName;
  return `/**
 * ${PascalName} Concept Factory
 *
 * Bare-minimum concept generated by SCS-Bridge Naming Wizard (M2-A1-D2).
 * Register Qualities + Principles as the SCP grows.
 */
import { createConcept } from 'stratimux';
import { ${camelName}Name, type ${PascalName}Qualities } from './${camelName}.type';
import { create${PascalName}State } from './${camelName}.state';

const ${camelName}Qualities: ${PascalName}Qualities = {
  // Add qualities here as the SCP grows
};

export const create${PascalName}Concept = () => {
  return createConcept(
    ${camelName}Name,
    create${PascalName}State(),
    ${camelName}Qualities,
    [],
  );
};
`;
}

// ============================================
// C727 · 5 · THE CADMIUM-LIKENESS EMIT SET (B1 · B2 · B3)
// ============================================
//
// The generated base concept alone is an ORPHAN — wired into no Client Muxium, rendered by no page.
// The Cadmium likeness (r4 Chain B) makes a minted S8 page self-muxify OUT OF THE BOX: its own page
// creates its own Client Muxium and muxifies THREE nodes — the generic suite8 face, THIS designation's
// dedicated concept, and the suiteCascade prior base (the S8RI relay carrying live Diamond/Onyx docs).
// These three template functions emit the additional files that close the orphan gap.

/**
 * B1 · the dedicated CLIENT concept face. Mirrors cadmium.concept.client.ts — reuses the generated
 * base .type (Name + Qualities type) + .state factory (client-safe · pure defaults), seeds an empty
 * client qualities map (grow later), and exports create<Pascal>ClientConcept() as the muxifiable node.
 */
function generateClientConceptFile(d: NameDerivation): string {
  const PascalName = d.designation;
  const camelName = d.conceptName;
  return `/**
 * ${PascalName} Client Concept Factory
 *
 * The DEDICATED client face muxified into this designation's own Client Muxium by
 * ${PascalName}Landing.vue (the Cadmium likeness). Reuses the base .type + .state; seeds an
 * empty client qualities map — add Client qualities here as the page grows.
 *
 * Higher-Order Composition: this stands as a base concept; the Landing page muxifies it as a
 * MuxonomicConcept node (Tier 2 · d.client.d.${camelName}.k.property.select()). No 3rd tier.
 *
 * Citation: cadmium.concept.client.ts (the dedicated-concept-per-S8 likeness).
 * Citation: STRATIMUX-REFERENCE.md "🎯 Essential Principles for Successful StratiDECK".
 */
import { createConcept } from 'stratimux';
import { ${camelName}Name, type ${PascalName}Qualities } from './${camelName}.type';
import { create${PascalName}State } from './${camelName}.state';

// Explicit quality mapping — NEVER typeof. Empty at mint; add Client qualities as the page grows.
const ${camelName}ClientQualities: ${PascalName}Qualities = {};

export const create${PascalName}ClientConcept = () => {
  return createConcept(
    ${camelName}Name,
    create${PascalName}State(),
    ${camelName}ClientQualities,
    [],
  );
};
`;
}

/**
 * B2 · the muxonomy wrapper + navigation + creator. Mirrors cadmium.muxonomy.ts — the MuxonomicConfig
 * paired with the client concept in the createClientMuxiumInstance array, PLUS the two exports the
 * build-time muxonomy registry scan (generateMuxonomyRegistry · npm run strativerse:scan) requires to
 * AUTO-REGISTER the page's route + sidebar nav (B4 · the automatic `scs suite8:page`):
 *   - export const <camel>Muxonomic  (the config · the registry's configMatch)
 *   - export function createMuxonomic<Pascal>()  (the MuxonomicConcept creator · the registry's
 *     creatorMatch · feeds ISLAND_CREATORS)
 *   - a navigation:{ pages:[{ componentPath }] } block  (the registry's hasNavigation + island harvest
 *     → the /<camel> route resolving to <Pascal>Landing.vue)
 * Minimal otherwise — no Diametric routes yet (those travel WITH suiteCascade · Cadmium note).
 *
 * Citation: cadmium.muxonomy.ts (the dedicated-concept muxonomy wrapper + navigation).
 * Citation: generateMuxonomyRegistry.quality.huirth.diameter.ts (the scan contract · configMatch +
 *           creatorMatch + hasNavigation + componentPath island harvest).
 * Citation: muxonomy.model.ts MuxonomicConfig.
 */
function generateMuxonomyFile(d: NameDerivation): string {
  const PascalName = d.designation;
  const camelName = d.conceptName;
  return `/**
 * ${PascalName} Muxonomy Configuration
 *
 * The MuxonomicConfig wrapper paired with create${PascalName}ClientConcept() in the
 * createClientMuxiumInstance array on ${PascalName}Landing.vue, plus the navigation + creator exports
 * the build-time registry scan harvests to AUTO-REGISTER the /${camelName} route + sidebar nav.
 * Minimal at mint — the InductionState filterKeys only; add demometers / actionExchange routes as
 * Client qualities land.
 *
 * Citation: cadmium.muxonomy.ts (the dedicated-concept muxonomy wrapper + navigation).
 * Citation: muxonomy.model.ts MuxonomicConfig.
 */
import {
  type MuxonomicConfig,
  type MuxonomicConcept,
  type NavigationConfig,
  type PageEntry,
  ChangeDetectionMode,
} from '../muxonomy/muxonomy.model';
import { create${PascalName}ClientConcept } from './${camelName}.concept.client';

const ${camelName}LandingPage: PageEntry = {
  path: '/${camelName}',
  label: '${PascalName}',
  order: 0,
  componentPath: '${camelName}/vue/${PascalName}Landing',
  isMain: true,
};

// B4 · the sidebar nav entry. isMainLanding stays FALSE at mint — the DEFAULT Home owns the landing
// until a user domain page claims it (the FT-009 correction · matches cadmium.muxonomy.ts).
export const ${camelName}Navigation: NavigationConfig = {
  isMainLanding: false,
  icon: '🎯',
  color: 'base',
  label: '${PascalName}',
  order: 5,
  pages: [${camelName}LandingPage],
};

export const ${camelName}Muxonomic: MuxonomicConfig<'${camelName}'> = {
  conceptName: '${camelName}',
  filterKeys: ['actionQue', 'filterKeys'],
  novelChange: {
    mode: ChangeDetectionMode.KeyedSelector,
  },
  // Nothing synced at mint (a client-local page · no Diametric routes yet). Add filterKeys here as
  // Client qualities that must broadcast to Huirth land.
  sync: {
    direction: 'toClient',
    filterKeys: [],
    novelChange: {
      mode: ChangeDetectionMode.KeyedSelector,
    },
  },
  demometers: {
    qualities: [],
    strategies: [],
    principles: [],
  },
  decks: {
    huirth: '${PascalName}HuirthDeck',
    client: '${PascalName}ClientDeck',
  },
  navigation: ${camelName}Navigation,
};

// The MuxonomicConcept creator the registry scan harvests into ISLAND_CREATORS (the createMuxonomic
// export the scan's creatorMatch requires). Pairs the dedicated client concept with its config.
export function createMuxonomic${PascalName}(): MuxonomicConcept<'${camelName}'> {
  return {
    concept: create${PascalName}ClientConcept(),
    muxonomy: ${camelName}Muxonomic,
  };
}
`;
}

/**
 * B3 · the self-muxifying Landing page. Mirrors CadmiumLanding's GPIM block (r4:563-579) modeled on
 * the in-repo Suite8Landing.vue: a 3-node createClientMuxiumInstance (generic suite8 + dedicated +
 * suiteCascade prior base) + GPIM bind/unbind + <Suite8CascadeDocs :designation> rendering THIS
 * designation's live Diamond/Onyx from its own Working/ pair (the full round-trip payoff).
 */
function generateLandingVue(d: NameDerivation): string {
  const PascalName = d.designation;
  const camelName = d.conceptName;
  return `<script setup lang="ts">
/**
 * ${PascalName} Landing — the self-muxifying Suite 8 page (the Cadmium likeness).
 *
 * This page creates its OWN Client Muxium and muxifies THREE nodes:
 *   1. createSuite8ClientConcept()   — the generic suite8 face (roster + docked cascade context)
 *   2. create${PascalName}ClientConcept() — THIS designation's DEDICATED concept (Tier 2 ·
 *                                      d.client.d.${camelName}.k.property.select())
 *   3. createSuiteCascadeConcept()   — the PRIOR base (S8RI) carrying live Diamond/Onyx docs
 *
 * <Suite8CascadeDocs :designation> reads THIS designation's own Cascades/Extended/${PascalName}/
 * Working/ pair via the extended auto-registration circuit — the founding writes the pair into
 * Working/, this page renders it live, and a page edit saves back into Working/ (round-trip).
 *
 * Citation: CadmiumLanding.vue (the GPIM self-muxify block · r4 Chain B).
 * Citation: Suite8Landing.vue (the in-repo createClientMuxiumInstance + GPIM bind/unbind pattern).
 */
import { onMounted, onUnmounted } from 'vue';
import type { Muxium } from 'stratimux';
import { createClientMuxiumInstance, type ClientMuxiumDeck } from '../../client/client.muxonomy';
// Node 1 · the generic suite8 face.
import { createSuite8ClientConcept } from '../../suite8/suite8.concept.client';
import { suite8Muxonomic } from '../../suite8/suite8.muxonomy';
// Node 2 · THIS designation's dedicated concept.
import { create${PascalName}ClientConcept } from '../${camelName}.concept.client';
import { ${camelName}Muxonomic } from '../${camelName}.muxonomy';
// Node 3 · the suiteCascade prior base (S8RI · live Diamond/Onyx relay).
import { createSuiteCascadeConcept } from '../../suiteCascade/suiteCascade.concept.client';
import { suiteCascadeMuxonomic } from '../../suiteCascade/suiteCascade.muxonomy';
// GPIM · Vue-layer Muxium binding into the universal scsBridge controller.
import { getGlobalScsBridgeController } from '../../scsBridge/scsBridgeController';
// The per-designation cascade docs pane (path-agnostic · reads Working/ live).
import Suite8CascadeDocs from '../../suite8/vue/components/Suite8CascadeDocs.vue';

let muxium: Muxium<ClientMuxiumDeck> | null = null;

onMounted(() => {
  // The 3-node self-muxify — the Cadmium likeness out of the box.
  muxium = createClientMuxiumInstance<ClientMuxiumDeck>(
    [
      { concept: createSuite8ClientConcept(), muxonomy: suite8Muxonomic },
      { concept: create${PascalName}ClientConcept(), muxonomy: ${camelName}Muxonomic },
      { concept: createSuiteCascadeConcept(), muxonomy: suiteCascadeMuxonomic },
    ],
    {
      title: '${PascalName}Landing',
      logging: true,
      storeDialog: true,
    },
  );

  // GPIM · bind this landing's Muxium into the universal scsBridge controller.
  const sbController = getGlobalScsBridgeController();
  if (sbController) sbController.setMuxium(muxium);
});

onUnmounted(() => {
  // GPIM cleanup · unbind controller from this landing's Muxium (mirror CadmiumLanding).
  const sbController = getGlobalScsBridgeController();
  if (sbController) sbController.setMuxium(null);
  if (muxium) muxium.close();
});
</script>

<template>
  <div class="${camelName}-landing">
    <header class="landing-header">
      <h1 class="hifi-heading spectrum-text">${PascalName}</h1>
    </header>
    <Suite8CascadeDocs :designation="'${PascalName}'" />
  </div>
</template>
`;
}

// ============================================
// MAIN ENTRY
// ============================================

/**
 * Generates the CADMIUM-LIKENESS concept bundle for a validated NameDerivation. File paths are
 * relative to SCP/src/ — the consuming Clone + Rename Engine (M2-A1-D3) prepends the absolute SCP
 * install path at write time.
 *
 * C727 · 5 · the emit set grew 3 → 6 so a minted S8 page self-muxifies OUT OF THE BOX (r4 Chain B):
 *   1. <name>.type.ts          — the base type (Name + State + Qualities type)
 *   2. <name>.state.ts         — the base state factory (client-safe · reused by the client face)
 *   3. <name>.concept.ts       — the base concept (Huirth-capable · empty qualities)
 *   4. <name>.concept.client.ts — B1 · the DEDICATED client face (create<Pascal>ClientConcept)
 *   5. <name>.muxonomy.ts       — B2 · the muxonomy wrapper (<camel>Muxonomic)
 *   6. vue/<Pascal>Landing.vue  — B3 · the self-muxifying page (3-node createClientMuxiumInstance)
 * The client face reuses the base .state factory (pure defaults · no server deps) rather than
 * emitting a separate client-state file, so the delta is 6 files, not 7. B4 (route + nav) is the
 * mint-time registration step, not a src file (Stage 6).
 */
export function generateBareMinimumConcept(d: NameDerivation): GeneratedConceptBundle {
  const dir = `concepts/${d.conceptName}`;
  const files: GeneratedConceptFile[] = [
    {
      relativePath: `${dir}/${d.conceptName}.type.ts`,
      content: generateTypeFile(d),
    },
    {
      relativePath: `${dir}/${d.conceptName}.state.ts`,
      content: generateStateFile(d),
    },
    {
      relativePath: `${dir}/${d.conceptName}.concept.ts`,
      content: generateConceptFile(d),
    },
    // C727 · 5 · B1 · the dedicated client concept face (the muxifiable node).
    {
      relativePath: `${dir}/${d.conceptName}.concept.client.ts`,
      content: generateClientConceptFile(d),
    },
    // C727 · 5 · B2 · the muxonomy wrapper paired with the client concept.
    {
      relativePath: `${dir}/${d.conceptName}.muxonomy.ts`,
      content: generateMuxonomyFile(d),
    },
    // C727 · 5 · B3 · the self-muxifying Landing page (3-node createClientMuxiumInstance · GPIM).
    {
      relativePath: `${dir}/vue/${d.designation}Landing.vue`,
      content: generateLandingVue(d),
    },
  ];
  return {
    files,
    conceptName: d.conceptName,
    designation: d.designation,
    fileCount: files.length,
  };
}
