import { writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'

const args = process.argv.slice(2)
const nameIdx = args.indexOf('--name')
const formatIdx = args.indexOf('--format')
const name = nameIdx >= 0 ? args[nameIdx + 1] : 'World'
const format = formatIdx >= 0 ? args[formatIdx + 1] : 'text'
const timestamp = new Date().toISOString()

mkdirSync('output', { recursive: true })

if (format === 'json') {
  const data = {
    greeting: `Hello, ${name}!`,
    suite: 'Hello World',
    skill: 'S1-Greeting',
    timestamp,
    format: 'json'
  }
  const outPath = join('output', 'greeting.json')
  writeFileSync(outPath, JSON.stringify(data, null, 2))
  console.log(outPath)
} else {
  const text = `Hello, ${name}! Generated by Suite 8 at ${timestamp}.`
  const outPath = join('output', 'greeting.txt')
  writeFileSync(outPath, text)
  console.log(outPath)
}
