/**
 * Muxonomy Registry - AUTO-GENERATED BY STRATIVERSE
 * DO NOT EDIT MANUALLY
 *
 * Regenerate with: npm run strativerse:scan
 * Generated: 2026-01-28T00:00:00.000Z
 *
 * Citation: SUITE-1-2-MUXONOMY-ISLANDS-ARCHITECTURE.md
 * Pattern: Build-time registry generation for Islands Architecture
 *
 * SCP Template: Empty registry — no muxonomic concepts registered locally.
 * Future: ADMIN_ICP StratiVERSE will manage entries in this file (historical project name; canonical successor is the SCP Suite 8 type · see Diamond SCP-3).
 */

import type { MuxonomicConfig, MuxonomicConcept } from './muxonomy/muxonomy.model';

/**
 * All registered muxonomy configurations with navigation
 * Used by: vue.principle.ts (shell generation)
 */
export const REGISTERED_MUXONOMICS: MuxonomicConfig[] = [];

/**
 * Vite entry points for island builds
 * Used by: vite.client.config.ts (rollupOptions.input)
 */
export const ISLAND_ENTRIES: Record<string, string> = {};

/**
 * Island creators for client hydration
 * Used by: main.ts (island hydration)
 */
export const ISLAND_CREATORS: Record<string, () => MuxonomicConcept> = {};

/**
 * Registry generation metadata
 */
export const REGISTRY_META = {
  generatedAt: '2026-01-28T00:00:00.000Z',
  conceptCount: 0,
  islandCount: 0,
};
